name: Selenium Test + Allure Report Deployment

on:
  push:
    branches: [ main ]

permissions:
  contents: write  # required for gh-pages deploy

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # 3) Stable Chrome + Chromedriver
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      # 4) Run tests (pom.xml is under ./src)
      - name: Run Selenium tests
        run: mvn -q -DskipTests=false clean test
        working-directory: ./src

      # 5) Sanity: do we have fresh Allure results?
      - name: Debug Allure results
        if: always()
        run: |
          echo "target dir:"
          ls -la ./src/target || true
          echo "allure-results:"
          ls -la ./src/target/allure-results || true
          echo "file count:" $(find ./src/target/allure-results -type f | wc -l || true)

      # 6) Generate Allure report (Maven plugin)
      - name: Generate Allure report
        run: mvn -q allure:report
        working-directory: ./src

      # 7) Deploy to GitHub Pages (fresh publish to avoid stale history)
      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/target/site/allure-maven-plugin
          force_orphan: true
          commit_message: "Allure report"