name: Selenium Test + Allure Report Deployment

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Run Selenium tests
        run: mvn -q -DskipTests=false -Dallure.results.directory=./target/allure-results clean test
        working-directory: ./src

      # Discover where the adapter wrote results; normalize to target/
      - name: Locate and normalize Allure results
        if: always()
        run: |
          echo "Searching for any allure-results directories..."
          find . -type d -name "allure-results" -maxdepth 4 -print
          # If results landed in ./src/allure-results (legacy default), move them
          if [ -d ./src/allure-results ]; then
            echo "Found ./src/allure-results — moving to ./src/target/allure-results"
            mkdir -p ./src/target/allure-results
            shopt -s nullglob
            mv ./src/allure-results/* ./src/target/allure-results/ || true
            rmdir ./src/allure-results || true
          fi
          echo "Final contents of ./src/target/allure-results:"
          ls -la ./src/target/allure-results || true
          echo "Removing zero-byte files (if any)..."
          find ./src/target/allure-results -type f -size 0 -print -delete || true

      - name: Generate Allure report
        run: mvn -q -Dallure.results.directory=./target/allure-results allure:report
        working-directory: ./src

      - name: Show generated Allure site
        run: |
          tree -L 2 ./src/target/site/allure-maven-plugin || ls -R ./src/target/site/allure-maven-plugin
          test -f ./src/target/site/allure-maven-plugin/index.html || (echo "index.html missing!" && exit 1)

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./src/target/site/allure-maven-plugin
          force_orphan: true
          enable_jekyll: false
          commit_message: "Allure report: ${{ github.sha }}"