name: Selenium Test + Allure Report Deployment

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # 3️⃣ Install Chrome and ChromeDriver for Selenium
      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable
      - name: Install ChromeDriver
        run: sudo apt-get install -y chromium-chromedriver

      # 4️⃣ Run Maven tests
      - name: Run Selenium tests
        run: mvn clean test
        working-directory: ./src  # Adjust path to pom.xml

      # 5️⃣ Generate Allure report
      - name: Generate Allure report
        run: mvn allure:report
        working-directory: ./src  # Same folder as pom.xml

      # 6️⃣ Verify Allure report files exist
      - name: List Allure report files
        run: ls -R ./src/target/site/allure-maven-plugin

      # 7️⃣ Deploy Allure report to GitHub Pages
      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/target/site/allure-maven-plugin
          destination_dir: .
          commit_message: "Deploy Allure report from GitHub Actions"
