- name: Run Selenium tests
  run: mvn -q -DskipTests=false clean test
  working-directory: ./src

- name: Debug Allure results
  if: always()
  run: |
    ls -la ./src/target/allure-results || true
    echo "files:" $(find ./src/target/allure-results -type f | wc -l || true)

- name: Generate Allure report
  run: mvn -q allure:report
  working-directory: ./src

- name: Deploy Allure report to GitHub Pages
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./src/target/site/allure-maven-plugin
    destination_dir: .