name: Selenium Test + Allure Report

on:
  push:
    branches:
      - main

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # 3. Install Chrome and ChromeDriver (for Selenium)
      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable
      - name: Install ChromeDriver
        run: sudo apt-get install -y chromium-chromedriver

      # 4. Run tests with Maven
      - name: Run Selenium tests
        run: mvn clean test

      # 5. Generate Allure report
      - name: Generate Allure report
        run: mvn allure:report

      # 6. Deploy report to GitHub Pages
      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/allure-maven-plugin
          # Optional: commit message
          commit_message: "Deploy Allure report from GitHub Actions"
