name: Selenium Test + Allure Report Deployment

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      # BEFORE tests — remove any stale results dirs from older configs
      - name: Clean old Allure folders
        run: |
          rm -rf ./src/allure-results ./allure-results
          mkdir -p ./src/target/allure-results

      # Run tests
      - name: Run Selenium tests
        run: mvn -q -DskipTests=false clean test
        working-directory: ./src

      # AFTER tests — list, and delete any zero-byte files
      - name: Sanity check Allure results
        if: always()
        run: |
          echo "Results path should be: ./src/target/allure-results"
          ls -la ./src/target/allure-results || true
          echo "Zero-byte files (if any):"
          find ./src/target/allure-results -type f -size 0 -print -delete || true

      - name: Generate Allure report
        run: mvn -q -Dallure.results.directory=./target/allure-results allure:report
        working-directory: ./src

      - name: Show generated Allure site
        run: |
          echo "Publishing directory tree:"
          tree -L 2 ./src/target/site/allure-maven-plugin || ls -R ./src/target/site/allure-maven-plugin
          test -f ./src/target/site/allure-maven-plugin/index.html || (echo "index.html missing!" && exit 1)

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./src/target/site/allure-maven-plugin
          force_orphan: true
          enable_jekyll: false
          commit_message: "Allure report: ${{ github.sha }}"